id: A55F8531A
title: Light Offering Prayer
type: translation
pechas:
- IA43FC73E
- I41985646
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:04:40.196874
  last_modified_at: 2023-01-04 13:04:40.196883
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IA43FC73E/AADC: CECA
  I41985646/2026: CECA
